create table sol_import(
  Contactnummer         varchar(14) NOT NULL PRIMARY KEY ,
  status                varchar(1)  DEFAULT 'N' ,
  typecontact           varchar(6)   ,
  `Externe Id`            varchar(14)  ,
  Adresvan              varchar(14)  ,
  Herkomst              varchar(32)  ,
  `Voorvoegsel Persoon`   varchar(20)  ,
  Voornaam              varchar(30)  ,
  Tussenvoegsel         varchar(20)  ,
  Achternaam            varchar(70)  ,
  tav                   varchar(70)  ,
  Roepnaam              varchar(40)  ,
  inforegel             varchar(70)  ,
  `Straat en huisnummer`  varchar(101) ,
  Straatnaam            varchar(70)  ,
  Huisnummer            varchar(30)  ,
  Postcode              varchar(30)  ,
  Plaats                varchar(70)  ,
  Land                  varchar(255) ,
  cod                   varchar(180) ,
  Gemaakt               date         ,
  Wijzigingsdatum       date         ,
  Wijziger              int(11)      ,
  Telefoon1             varchar(255) ,
  Telefoon2             varchar(255) ,
  Telefoon3             varchar(255) ,
  Telefoon4             varchar(255) ,
  Telefoon5             varchar(255) ,
  Telefoon6             varchar(255) ,
  Emailadressen         varchar(255) ,
  iban1                 varchar(255) ,
  bic1                  varchar(255) ,
  naam1                 varchar(255) ,
  plaats1               varchar(255) ,
  iban2                 varchar(255) ,
  bic2                  varchar(255) ,
  naam2                 varchar(255) ,
  plaats2               varchar(255) ,
  iban3                 varchar(255) ,
  bic3                  varchar(255) ,
  naam3                 varchar(255) ,
  plaats3               varchar(255) ,
  iban4                 varchar(255) ,
  bic4                  varchar(255) ,
  naam4                 varchar(255) ,
  plaats4               varchar(255) ,
  iban5                 varchar(255) ,
  bic5                  varchar(255) ,
  naam5                 varchar(255) ,
  plaats5               varchar(255)
)
